import {
  allEarthCards,
  earthCard,
  rockCard,
  sandCard,
  treeCard,
  leafCard,
  quakeStrikeCard,
  tremorCard,
  avalancheCard,
  dustDevilCard,
  earthQuakeCard,
} from './earthCards';

import {
  allAirCards,
  airCard,
  cloudCard,
  lightningCard,
  windCard,
  rainCard,
  featherCard,
  skyDiveCard,
  gustCannonCard,
  aerialAssaultCard,
  hurricaneCard,
} from './airCards.js';

import {
  allFireCards,
  fireCard,
  fireballCard,
  lavaCard,
  rainOfFireCard,
  volcanoCard,
  ashRainCard,
  ignitionStrikeCard,
  pyroclasmCard,
  fireWhipCard,
  burningMeteorCard,
} from './fireCards.js';
import {
  waterCard,
  aquaSlashCard,
  waterFallCard,
  iceCard,
  blizzardCard,
  iceSpikeCard,
  oceanCurrentCard,
  highTideCard,
  coralCrushCard,
  tsunamiCard,
  allWaterCards,
} from './waterCards.js';

const allElementalCards = [
  ...allEarthCards,
  ...allWaterCards,
  ...allAirCards,
  ...allFireCards,
];

export {
  allElementalCards,
  allEarthCards,
  earthCard,
  rockCard,
  sandCard,
  treeCard,
  leafCard,
  quakeStrikeCard,
  tremorCard,
  avalancheCard,
  dustDevilCard,
  earthQuakeCard,
  allAirCards,
  airCard,
  cloudCard,
  lightningCard,
  windCard,
  rainCard,
  featherCard,
  skyDiveCard,
  gustCannonCard,
  aerialAssaultCard,
  hurricaneCard,
  allFireCards,
  fireCard,
  fireballCard,
  lavaCard,
  rainOfFireCard,
  volcanoCard,
  ashRainCard,
  ignitionStrikeCard,
  pyroclasmCard,
  fireWhipCard,
  burningMeteorCard,
  waterCard,
  aquaSlashCard,
  waterFallCard,
  iceCard,
  blizzardCard,
  iceSpikeCard,
  oceanCurrentCard,
  highTideCard,
  coralCrushCard,
  tsunamiCard,
  allWaterCards,
};
