import { img } from "../assets/imgur.js";
const mainStory = [
  {
    id: 0,
    title: "Introduction",
    hasViewed: false,
    chapterTitle: "Eldridia's Elements",
    content:
      "As the first sparks ignited I knew... The birth of what was to come would be the greatest of all my creations.",
    paths: "/game/story",
    backgrounds: img.backgrounds.introduction.sceneOne,
    speakers: img.mainCharacters.eldrida,
    isReward: false,
    rewards: [],
    animations: [],
    storyPath: "Introduction",
    music: [],
    leftRight: true,
    voiceClips: [],
    pathIsValid: false,
  },
  {
    id: 1,
    title: "introduction",
    hasViewed: false,
    chapterTitle: "The Changing Winds",
    content:
      "In my infinite wisdom I created the elements, and with them I created the world.",
    paths: "/game/story",
    backgrounds: img.backgrounds.introduction.sceneTwo,
    speaker: img.mainCharacters.eldrida,
    isReward: false,
    rewards: [],
    animations: [],
    storyPath: "Introduction",
    music: [],
    leftRight: true,
    voiceClips: [],
    pathIsValid: false,
  },
  {
    id: 2,
    title: "introduction",
    hasViewed: false,
    chapterTitle: "The Changing Winds",
    content:
      "I created the world with the elements in balance, and with the elements in balance the world was at peace.",
    paths: "/game/story",
    backgrounds: img.backgrounds.introduction.sceneThree,
    speaker: img.mainCharacters.eldrida,
    isReward: false,
    rewards: [],
    animations: [],
    storyPath: "Introduction",
    music: [],
    leftRight: true,
    voiceClips: [],
    pathIsValid: false,
  },
  {
    id: 3,
    title: "introduction",
    hasViewed: false,
    chapterTitle: "The Changing Winds",
    content:
      "I have given my creations free will, but at what cost? As now some of my own creations are seeking to disrupt the very balance i have created, and desecrate the very land on which they stand.",
    paths: "/game/story",
    backgrounds: img.backgrounds.introduction.sceneFour,
    speaker: img.mainCharacters.eldrida,
    isReward: false,
    rewards: [],
    animations: [],
    storyPath: "Introduction",
    music: [],
    leftRight: true,
    voiceClips: [],
    pathIsValid: false,
  },
  {
    id: 4,
    title: "introduction",
    hasViewed: false,
    chapterTitle: "The Changing Winds",
    content:
      "That child of mine that seeks to destroy me must be stopped. But I'll shall not interfere directly. Let things unfold.....",
    paths: "/dashboard",
    backgrounds: img.backgrounds.introduction.sceneFive,
    speaker: img.mainCharacters.eldrida,
    isReward: false,
    rewards: [],
    animations: [],
    storyPath: "Introduction",
    music: [],
    leftRight: true,
    voiceClips: [],
    pathIsValid: true,
  },
];

export { mainStory };

//TODO: Condense this with arrays for content
