const storyOne = [
  {
    id: 0,
    chapterTitle: "Eldridia's Elements",
    playerText: "Welcome to Eldridia's Elements",
    path: "/dashboard/story",
    background: "https://i.imgur.com/xZvK1SL.jpg",
    speakerImg: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 1,
    chapterTitle: "The Lost City",
    playerText: "ACT ONE",
    path: "/dashboard/story",
    background: "https://i.imgur.com/xZvK1SL.jpg",
    speakerImg: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 2,
    chapterTitle: "The Town of Miria",
    playerText: "ACT ONE, Prepare your paryt for battle",
    path: "/dashboard/overview",
    background: "https://i.imgur.com/wRbZ69T.jpg",
    speakerImg: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    rewards: [],
    pathIsValid: true,
  },

  {
    id: 3,
    chapterTitle: "The Mysterious Stranger",
    npcText:
      "You see a stranger beeing attacked on the road by a group of monsters.",
    background: "https://i.imgur.com/bqUWDWl.jpg",
    path: "/dashboard/story",
    speakerImg: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 4,
    chapterTitle: "The Mysterious Stranger",
    npcText: "AAAAAAAAAAHHHHHHHHHHHHHH",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 5,
    chapterTitle: "The Mysterious Stranger",
    playerText: "We need to go save him!",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",

    nameOfSpeaker: "The Party",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 6,
    chapterTitle: "The Mysterious Stranger",
    npcText: "AAAAAAAHHHHHHHHHH",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/play",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    rewards: [],
    pathIsValid: true,
  },
  {
    id: 7,
    chapterTitle: "The Mysterious Stranger is saved",
    npcText: "Thank you for saving me!",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 8,
    chapterTitle: "The Mysterious Stranger is saved",
    playerText: "What is your name?",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "The Party",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 9,
    chapterTitle: "The Mysterious Stranger is saved",
    npcText: "My name is... I don't know...",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 10,
    chapterTitle: "The Mysterious Stranger is saved",
    npcText: "I don't remember anything...",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 11,
    chapterTitle: "The Mysterious Stranger is saved",
    playerText: "we will help you find out who you are",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "The Party",
    rewards: [],
    pathIsValid: true,
  },
  {
    id: 12,
    chapterTitle: "The Mysterious Stranger is saved",
    npcText: "Thank you!",
    background: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/play",
    speakerImg: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    rewards: [],
    pathIsValid: false,
  },
];

// const StoryLine = {

//   mainStory:

// }

export { storyOne };
