const storyOne = [
  {
    id: 0,
    chapterTitle: "Eldridia's Elements",
    playerText: "Welcome to Eldridia's Elements",
    path: '/dashboard/story',
    background: '',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'Narrator',
    isReward: false,
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 1,
    chapterTitle: 'The Lost City',
    npcText: 'ACT ONE',
    path: '/dashboard/story',
    background: '',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'Narrator',
    isReward: false,
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 2,
    chapterTitle: 'The Town of Miria',
    playerText: 'ACT ONE, Prepare your paryt for battle',
    path: '/dashboard/overview',
    background: '',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'Narrator',
    isReward: false,
    rewards: [],
    pathIsValid: true,
  },

  {
    id: 3,
    chapterTitle: 'The Mysterious Stranger',
    npcText:
      'You see a stranger beeing attacked on the road by a group of monsters.',
    background: '',
    path: '/dashboard/story',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    isReward: false,
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'Narrator',
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 4,
    chapterTitle: 'The Mysterious Stranger',
    npcText: 'AAAAAAAAAAHHHHHHHHHHHHHH',
    background: '',
    path: '/dashboard/story',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'Stranger On the Road',
    isReward: false,
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 5,
    chapterTitle: 'The Mysterious Stranger',
    playerText: 'We need to go save him!',
    background: '',
    path: '/dashboard/story',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'The Party',
    isReward: false,
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 6,
    chapterTitle: 'The Mysterious Stranger',
    npcText: 'AAAAAAAHHHHHHHHHH',
    background: 'https://i.imgur.com/CrcBLo1.jpg',
    path: '/dashboard/play',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'Stranger On the Road',
    isReward: false,
    rewards: [],
    pathIsValid: true,
  },
  {
    id: 7,
    chapterTitle: 'The Mysterious Stranger is saved',
    npcText: 'Thank you for saving me!',
    background: 'https://i.imgur.com/CrcBLo1.jpg',
    path: '/dashboard/story',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'Stranger On the Road',
    isReward: false,
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 8,
    chapterTitle: 'The Mysterious Stranger is saved',
    playerText: 'What is your name?',
    background: 'https://i.imgur.com/CrcBLo1.jpg',
    path: '/dashboard/story',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    nameOfSpeaker: 'The Party',
    isReward: false,
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 9,
    chapterTitle: 'The Mysterious Stranger is saved',
    npcText: "My name is... I don't know...",
    background: 'https://i.imgur.com/CrcBLo1.jpg',
    path: '/dashboard/story',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    isReward: false,
    nameOfSpeaker: 'Stranger On the Road',
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 10,
    chapterTitle: 'The Mysterious Stranger is saved',
    npcText: "I don't remember anything...",
    background: 'https://i.imgur.com/CrcBLo1.jpg',
    path: '/dashboard/story',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    isReward: false,
    nameOfSpeaker: 'Stranger On the Road',
    rewards: [],
    pathIsValid: false,
  },
  {
    id: 11,
    chapterTitle: 'The Mysterious Stranger is saved',
    playerText: 'we will help you find out who you are',
    background: 'https://i.imgur.com/CrcBLo1.jpg',
    path: '/dashboard',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    isReward: false,
    nameOfSpeaker: 'The Party',
    rewards: [],
    pathIsValid: true,
  },
  {
    id: 12,
    chapterTitle: 'The Mysterious Stranger is saved',
    npcText: 'Thank you!',
    background: 'https://i.imgur.com/CrcBLo1.jpg',
    path: '/dashboard/play',
    npcImg: 'https://i.imgur.com/ZHLh0zg.png',
    playerImg: 'https://i.imgur.com/N4X30zf.png',
    isReward: false,
    nameOfSpeaker: 'Stranger On the Road',
    rewards: [],
    pathIsValid: false,
  },
];

// const StoryLine = {

//   mainStory:

// }

export { storyOne };
