const storyOne = [
  {
    id: 0,
    title: "Eldridia's Elements",
    playerText: "Welcome to Eldridia's Elements",
    path: "/dashboard/story",
    image: "https://i.imgur.com/xZvK1SL.jpg",
    imageIcon: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    pathIsValid: false,
  },
  {
    id: 1,
    title: "The Lost City",
    playerText: "ACT ONE",
    path: "/dashboard/story",
    image: "https://i.imgur.com/xZvK1SL.jpg",
    imageIcon: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    pathIsValid: false,
  },
  {
    id: 2,
    title: "The Town of Miria",
    playerText: "ACT ONE, Prepare your paryt for battle",
    path: "/dashboard/overview",
    image: "https://i.imgur.com/wRbZ69T.jpg",
    imageIcon: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    pathIsValid: true,
  },

  {
    id: 3,
    title: "The Mysterious Stranger",
    npcText:
      "You see a stranger beeing attacked on the road by a group of monsters.",
    image: "https://i.imgur.com/bqUWDWl.jpg",
    path: "/dashboard/story",
    imageIcon: "https://i.imgur.com/q2ZMUGC.png",
    nameOfSpeaker: "Narrator",
    pathIsValid: false,
  },
  {
    id: 4,
    title: "The Mysterious Stranger",
    npcText: "AAAAAAAAAAHHHHHHHHHHHHHH",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    pathIsValid: false,
  },
  {
    id: 5,
    title: "The Mysterious Stranger",
    playerText: "We need to go save him!",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",

    nameOfSpeaker: "The Party",
    pathIsValid: false,
  },
  {
    id: 6,
    title: "The Mysterious Stranger",
    npcText: "AAAAAAAHHHHHHHHHH",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/play",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    pathIsValid: true,
  },
  {
    id: 7,
    title: "The Mysterious Stranger is saved",
    npcText: "Thank you for saving me!",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    pathIsValid: false,
  },
  {
    id: 8,
    title: "The Mysterious Stranger is saved",
    playerText: "What is your name?",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "The Party",
    pathIsValid: false,
  },
  {
    id: 9,
    title: "The Mysterious Stranger is saved",
    npcText: "My name is... I don't know...",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    pathIsValid: false,
  },
  {
    id: 10,
    title: "The Mysterious Stranger is saved",
    npcText: "I don't remember anything...",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/story",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    pathIsValid: false,
  },
  {
    id: 11,
    title: "The Mysterious Stranger is saved",
    playerText: "we will help you find out who you are",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "The Party",
    pathIsValid: true,
  },
  {
    id: 12,
    title: "The Mysterious Stranger is saved",
    npcText: "Thank you!",
    image: "https://i.imgur.com/CrcBLo1.jpg",
    path: "/dashboard/play",
    imageIcon: "https://i.imgur.com/jWo5uD3.png",
    nameOfSpeaker: "Stranger On the Road",
    pathIsValid: false,
  },
];

export { storyOne };
